-- =============================================================
-- RUCOS V53 - ĐỐI SOÁT TÀI CHÍNH SHOPEE
-- Chạy sau V52. An toàn khi chạy lại.
-- =============================================================

create table if not exists public.finance_imports (
    id uuid primary key default gen_random_uuid(),
    file_hash text not null unique,
    file_name text not null default '',
    file_size bigint not null default 0,
    imported_at timestamptz not null default now(),
    period_from date,
    period_to date,
    row_count integer not null default 0,
    gross_total numeric(20,2) not null default 0,
    fee_total numeric(20,2) not null default 0,
    discount_total numeric(20,2) not null default 0,
    refund_total numeric(20,2) not null default 0,
    net_total numeric(20,2) not null default 0,
    mapping jsonb not null default '{}'::jsonb,
    created_by uuid default auth.uid(),
    created_email text not null default ''
);

create table if not exists public.finance_rows (
    id bigint generated by default as identity primary key,
    import_id uuid not null references public.finance_imports(id) on delete cascade,
    row_no integer not null,
    order_id text not null default '',
    transaction_date date,
    payout_date date,
    payout_id text not null default '',
    payment_status text not null default '',
    gross numeric(20,2) not null default 0,
    commission_fee numeric(20,2) not null default 0,
    service_fee numeric(20,2) not null default 0,
    transaction_fee numeric(20,2) not null default 0,
    shipping_fee numeric(20,2) not null default 0,
    voucher_cost numeric(20,2) not null default 0,
    refund_amount numeric(20,2) not null default 0,
    other_fee numeric(20,2) not null default 0,
    adjustment numeric(20,2) not null default 0,
    net_amount numeric(20,2) not null default 0,
    expected_net numeric(20,2) not null default 0,
    variance numeric(20,2) not null default 0,
    formula_comparable boolean not null default false,
    raw jsonb not null default '{}'::jsonb,
    unique(import_id,row_no)
);

create index if not exists idx_finance_rows_import on public.finance_rows(import_id);
create index if not exists idx_finance_rows_order on public.finance_rows(order_id) where order_id <> '';
create index if not exists idx_finance_rows_payout on public.finance_rows(payout_id) where payout_id <> '';

alter table public.finance_imports enable row level security;
alter table public.finance_rows enable row level security;

drop policy if exists finance_imports_select_authenticated on public.finance_imports;
create policy finance_imports_select_authenticated on public.finance_imports for select to authenticated using (true);
drop policy if exists finance_rows_select_authenticated on public.finance_rows;
create policy finance_rows_select_authenticated on public.finance_rows for select to authenticated using (true);

grant select on public.finance_imports to authenticated;
grant select on public.finance_rows to authenticated;

create or replace function public.begin_finance_import_v53(p_import jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text := public.app_current_role();
    v_id uuid;
begin
    if v_role not in ('ADMIN','KETOAN') then
        raise exception 'ROLE_FORBIDDEN_FINANCE_UPLOAD';
    end if;

    insert into public.finance_imports(
        file_hash,file_name,file_size,period_from,period_to,row_count,
        gross_total,fee_total,discount_total,refund_total,net_total,mapping,
        created_by,created_email,imported_at
    ) values (
        coalesce(p_import->>'fileHash',''),
        coalesce(p_import->>'fileName',''),
        coalesce((p_import->>'fileSize')::bigint,0),
        nullif(p_import->>'periodFrom','')::date,
        nullif(p_import->>'periodTo','')::date,
        coalesce((p_import->>'rowCount')::integer,0),
        coalesce((p_import->>'grossTotal')::numeric,0),
        coalesce((p_import->>'feeTotal')::numeric,0),
        coalesce((p_import->>'discountTotal')::numeric,0),
        coalesce((p_import->>'refundTotal')::numeric,0),
        coalesce((p_import->>'netTotal')::numeric,0),
        coalesce(p_import->'mapping','{}'::jsonb),
        auth.uid(),coalesce(auth.jwt()->>'email',''),now()
    )
    on conflict(file_hash) do update set
        file_name=excluded.file_name,
        file_size=excluded.file_size,
        period_from=excluded.period_from,
        period_to=excluded.period_to,
        row_count=excluded.row_count,
        gross_total=excluded.gross_total,
        fee_total=excluded.fee_total,
        discount_total=excluded.discount_total,
        refund_total=excluded.refund_total,
        net_total=excluded.net_total,
        mapping=excluded.mapping,
        created_by=auth.uid(),
        created_email=coalesce(auth.jwt()->>'email',''),
        imported_at=now()
    returning id into v_id;

    delete from public.finance_rows where import_id=v_id;
    return jsonb_build_object('import_id',v_id);
end;
$$;

create or replace function public.append_finance_rows_v53(p_import_id uuid,p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_role text := public.app_current_role();
    v_count integer := 0;
begin
    if v_role not in ('ADMIN','KETOAN') then raise exception 'ROLE_FORBIDDEN_FINANCE_UPLOAD'; end if;
    if not exists(select 1 from public.finance_imports where id=p_import_id) then raise exception 'FINANCE_IMPORT_NOT_FOUND'; end if;

    insert into public.finance_rows(
        import_id,row_no,order_id,transaction_date,payout_date,payout_id,payment_status,
        gross,commission_fee,service_fee,transaction_fee,shipping_fee,voucher_cost,refund_amount,other_fee,adjustment,
        net_amount,expected_net,variance,formula_comparable,raw
    )
    select
        p_import_id,
        coalesce(nullif(x.elem->>'rowNo','')::integer,x.ord::integer),
        coalesce(x.elem->>'orderId',''),
        nullif(x.elem->>'transactionDate','')::date,
        nullif(x.elem->>'payoutDate','')::date,
        coalesce(x.elem->>'payoutId',''),
        coalesce(x.elem->>'paymentStatus',''),
        coalesce((x.elem->>'gross')::numeric,0),
        coalesce((x.elem->>'commissionFee')::numeric,0),
        coalesce((x.elem->>'serviceFee')::numeric,0),
        coalesce((x.elem->>'transactionFee')::numeric,0),
        coalesce((x.elem->>'shippingFee')::numeric,0),
        coalesce((x.elem->>'voucherCost')::numeric,0),
        coalesce((x.elem->>'refundAmount')::numeric,0),
        coalesce((x.elem->>'otherFee')::numeric,0),
        coalesce((x.elem->>'adjustment')::numeric,0),
        coalesce((x.elem->>'netAmount')::numeric,0),
        coalesce((x.elem->>'expectedNet')::numeric,0),
        coalesce((x.elem->>'variance')::numeric,0),
        coalesce((x.elem->>'formulaComparable')::boolean,false),
        coalesce(x.elem->'raw','{}'::jsonb)
    from jsonb_array_elements(coalesce(p_rows,'[]'::jsonb)) with ordinality as x(elem,ord)
    on conflict(import_id,row_no) do update set
        order_id=excluded.order_id,transaction_date=excluded.transaction_date,payout_date=excluded.payout_date,
        payout_id=excluded.payout_id,payment_status=excluded.payment_status,gross=excluded.gross,
        commission_fee=excluded.commission_fee,service_fee=excluded.service_fee,transaction_fee=excluded.transaction_fee,
        shipping_fee=excluded.shipping_fee,voucher_cost=excluded.voucher_cost,refund_amount=excluded.refund_amount,
        other_fee=excluded.other_fee,adjustment=excluded.adjustment,net_amount=excluded.net_amount,
        expected_net=excluded.expected_net,variance=excluded.variance,formula_comparable=excluded.formula_comparable,raw=excluded.raw;

    get diagnostics v_count = row_count;
    return jsonb_build_object('saved',v_count);
end;
$$;

create or replace function public.admin_delete_finance_import_v53(p_import_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
    if public.app_current_role() <> 'ADMIN' then raise exception 'ROLE_FORBIDDEN_FINANCE_DELETE'; end if;
    delete from public.finance_imports where id=p_import_id;
    return true;
end;
$$;

revoke all on function public.begin_finance_import_v53(jsonb) from public;
revoke all on function public.append_finance_rows_v53(uuid,jsonb) from public;
revoke all on function public.admin_delete_finance_import_v53(uuid) from public;
grant execute on function public.begin_finance_import_v53(jsonb) to authenticated;
grant execute on function public.append_finance_rows_v53(uuid,jsonb) to authenticated;
grant execute on function public.admin_delete_finance_import_v53(uuid) to authenticated;

create or replace function public.app_health_check()
returns jsonb
language sql
security definer
set search_path = public
as $$
select jsonb_build_object(
    'ok', true,
    'version', 'V53',
    'role', public.app_current_role(),
    'tables', jsonb_build_object(
        'app_user_roles', to_regclass('public.app_user_roles') is not null,
        'invoice_imports', to_regclass('public.invoice_imports') is not null,
        'invoice_groups', to_regclass('public.invoice_groups') is not null,
        'invoice_lines', to_regclass('public.invoice_lines') is not null,
        'invoice_order_links', to_regclass('public.invoice_order_links') is not null,
        'inventory_return_receipts', to_regclass('public.inventory_return_receipts') is not null,
        'finance_imports', to_regclass('public.finance_imports') is not null,
        'finance_rows', to_regclass('public.finance_rows') is not null
    ),
    'v41', jsonb_build_object(
        'invoice_import_order_ref_header', exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoice_imports' and column_name='order_ref_header'),
        'invoice_import_order_ref_line_count', exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoice_imports' and column_name='order_ref_line_count'),
        'invoice_line_order_ref', exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoice_lines' and column_name='order_ref'),
        'invoice_line_order_ref_source', exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoice_lines' and column_name='order_ref_source')
    ),
    'v47', jsonb_build_object(
        'stocktake_baseline_date', exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='baseline_date'),
        'stocktake_theoretical_qty', exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='theoretical_qty'),
        'stocktake_variance_qty', exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='variance_qty'),
        'stocktake_variance_value', exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='variance_value'),
        'stocktake_reconcile_status', exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='reconcile_status')
    ),
    'v50', jsonb_build_object('invoice_order_links_ready', to_regclass('public.invoice_order_links') is not null),
    'v51', jsonb_build_object(
        'return_receipts_ready', to_regclass('public.inventory_return_receipts') is not null,
        'confirm_return_rpc', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='confirm_inventory_return_v51'),
        'reverse_return_rpc', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reverse_inventory_return_v51')
    ),
    'v52', jsonb_build_object(
        'inventory_lead_time_days', exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_items' and column_name='lead_time_days'),
        'inventory_target_cover_days', exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_items' and column_name='target_cover_days')
    ),
    'v53', jsonb_build_object(
        'finance_imports_ready', to_regclass('public.finance_imports') is not null,
        'finance_rows_ready', to_regclass('public.finance_rows') is not null,
        'finance_begin_rpc', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='begin_finance_import_v53'),
        'finance_append_rpc', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='append_finance_rows_v53'),
        'finance_delete_rpc', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_delete_finance_import_v53')
    ),
    'rpcs', jsonb_build_object(
        'app_user_context', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='app_user_context'),
        'admin_list_user_roles', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_list_user_roles'),
        'admin_set_user_role', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_set_user_role'),
        'replace_shift_data', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='replace_shift_data'),
        'save_invoice_history', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_invoice_history'),
        'confirm_inventory_return_v51', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='confirm_inventory_return_v51'),
        'reverse_inventory_return_v51', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reverse_inventory_return_v51'),
        'begin_finance_import_v53', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='begin_finance_import_v53'),
        'append_finance_rows_v53', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='append_finance_rows_v53'),
        'admin_delete_finance_import_v53', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_delete_finance_import_v53')
    )
);
$$;

revoke all on function public.app_health_check() from public;
grant execute on function public.app_health_check() to authenticated;
notify pgrst, 'reload schema';
select public.app_health_check() as v53_health_check;
