-- =============================================================
-- RUCOS V39 - LỊCH SỬ HÓA ĐƠN SUPABASE CLOUD
-- Chạy TOÀN BỘ script này 1 lần trong Supabase SQL Editor.
-- An toàn khi chạy lại: dùng IF NOT EXISTS / CREATE OR REPLACE.
-- =============================================================

create extension if not exists pgcrypto;

-- -------------------------------------------------------------
-- 1. Header mỗi lần upload file hóa đơn
-- -------------------------------------------------------------
create table if not exists public.invoice_imports (
    id uuid primary key default gen_random_uuid(),
    file_fingerprint text not null unique,
    file_name text not null default '',
    imported_at timestamptz not null default now(),
    date_from date,
    date_to date,
    source_row_count integer not null default 0,
    issued_line_count integer not null default 0,
    unissued_line_count integer not null default 0,
    invoice_count integer not null default 0,
    product_count integer not null default 0,
    total_quantity numeric not null default 0,
    vat_total numeric not null default 0,
    payment_total numeric not null default 0,
    pre_tax_total numeric not null default 0,
    created_by uuid,
    created_email text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists idx_invoice_imports_imported_at
    on public.invoice_imports(imported_at desc);

create index if not exists idx_invoice_imports_date_range
    on public.invoice_imports(date_from, date_to);

-- -------------------------------------------------------------
-- 2. Bảng đã gom theo tên sản phẩm (dùng để khôi phục giao diện)
-- -------------------------------------------------------------
create table if not exists public.invoice_groups (
    id bigint generated by default as identity primary key,
    import_id uuid not null references public.invoice_imports(id) on delete cascade,
    sort_order integer not null default 0,
    product_name text not null default '',
    quantity numeric not null default 0,
    vat numeric not null default 0,
    payment numeric not null default 0,
    pre_tax numeric not null default 0,
    promo boolean not null default false
);

create index if not exists idx_invoice_groups_import
    on public.invoice_groups(import_id, sort_order);

-- -------------------------------------------------------------
-- 3. Dòng chi tiết hóa đơn - chuẩn bị cho V41 ghép MISA <-> Shopee
-- -------------------------------------------------------------
create table if not exists public.invoice_lines (
    id bigint generated by default as identity primary key,
    import_id uuid not null references public.invoice_imports(id) on delete cascade,
    sort_order integer not null default 0,
    invoice_no text not null default '',
    invoice_date date,
    product_code text not null default '',
    product_name text not null default '',
    quantity numeric not null default 0,
    vat numeric not null default 0,
    payment numeric not null default 0,
    pre_tax numeric not null default 0,
    promo boolean not null default false,
    promo_flag text not null default '',
    tax_status text not null default '',
    invoice_status text not null default '',
    issued boolean not null default true
);

create index if not exists idx_invoice_lines_import
    on public.invoice_lines(import_id, sort_order);

create index if not exists idx_invoice_lines_invoice_no
    on public.invoice_lines(invoice_no);

create index if not exists idx_invoice_lines_invoice_date
    on public.invoice_lines(invoice_date);

create index if not exists idx_invoice_lines_product_code
    on public.invoice_lines(product_code);

-- -------------------------------------------------------------
-- 4. RLS: người đã đăng nhập được XEM.
--    Ghi/Xóa đi qua RPC để tránh nhân viên xóa trực tiếp.
-- -------------------------------------------------------------
alter table public.invoice_imports enable row level security;
alter table public.invoice_groups enable row level security;
alter table public.invoice_lines enable row level security;

drop policy if exists invoice_imports_select_auth on public.invoice_imports;
create policy invoice_imports_select_auth
on public.invoice_imports
for select
to authenticated
using (true);

drop policy if exists invoice_groups_select_auth on public.invoice_groups;
create policy invoice_groups_select_auth
on public.invoice_groups
for select
to authenticated
using (true);

drop policy if exists invoice_lines_select_auth on public.invoice_lines;
create policy invoice_lines_select_auth
on public.invoice_lines
for select
to authenticated
using (true);

-- Không tạo INSERT/UPDATE/DELETE policy trực tiếp.
-- Web ghi bằng RPC save_invoice_history.
-- Web xóa bằng RPC admin_delete_invoice_history + kiểm tra email ADMIN.

-- -------------------------------------------------------------
-- 5. RPC lưu một import + groups + lines trong CÙNG transaction
--    Nếu fingerprint đã tồn tại -> trả ID cũ, duplicate=true.
-- -------------------------------------------------------------
create or replace function public.save_invoice_history(
    p_import jsonb,
    p_groups jsonb default '[]'::jsonb,
    p_lines jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user uuid;
    v_email text;
    v_id uuid;
    v_fingerprint text;
begin
    v_user := auth.uid();

    if v_user is null then
        raise exception 'Not authenticated';
    end if;

    v_email := coalesce(auth.jwt() ->> 'email', '');
    v_fingerprint := nullif(trim(p_import ->> 'fileFingerprint'), '');

    if v_fingerprint is null then
        raise exception 'Missing file fingerprint';
    end if;

    select id
    into v_id
    from public.invoice_imports
    where file_fingerprint = v_fingerprint
    limit 1;

    if v_id is not null then
        return jsonb_build_object(
            'id', v_id,
            'duplicate', true
        );
    end if;

    insert into public.invoice_imports (
        file_fingerprint,
        file_name,
        imported_at,
        date_from,
        date_to,
        source_row_count,
        issued_line_count,
        unissued_line_count,
        invoice_count,
        product_count,
        total_quantity,
        vat_total,
        payment_total,
        pre_tax_total,
        created_by,
        created_email
    )
    values (
        v_fingerprint,
        coalesce(p_import ->> 'fileName', ''),
        coalesce(nullif(p_import ->> 'importedAt', '')::timestamptz, now()),
        nullif(p_import ->> 'dateFrom', '')::date,
        nullif(p_import ->> 'dateTo', '')::date,
        coalesce((p_import ->> 'sourceRowCount')::integer, 0),
        coalesce((p_import ->> 'issuedLineCount')::integer, 0),
        coalesce((p_import ->> 'unissuedLineCount')::integer, 0),
        coalesce((p_import ->> 'invoiceCount')::integer, 0),
        coalesce((p_import ->> 'productCount')::integer, 0),
        coalesce((p_import ->> 'totalQuantity')::numeric, 0),
        coalesce((p_import ->> 'vatTotal')::numeric, 0),
        coalesce((p_import ->> 'paymentTotal')::numeric, 0),
        coalesce((p_import ->> 'preTaxTotal')::numeric, 0),
        v_user,
        v_email
    )
    returning id into v_id;

    insert into public.invoice_groups (
        import_id,
        sort_order,
        product_name,
        quantity,
        vat,
        payment,
        pre_tax,
        promo
    )
    select
        v_id,
        coalesce((x.elem ->> 'sortOrder')::integer, x.ordinality::integer),
        coalesce(x.elem ->> 'productName', ''),
        coalesce((x.elem ->> 'quantity')::numeric, 0),
        coalesce((x.elem ->> 'vat')::numeric, 0),
        coalesce((x.elem ->> 'payment')::numeric, 0),
        coalesce((x.elem ->> 'preTax')::numeric, 0),
        coalesce((x.elem ->> 'promo')::boolean, false)
    from jsonb_array_elements(coalesce(p_groups, '[]'::jsonb))
         with ordinality as x(elem, ordinality);

    insert into public.invoice_lines (
        import_id,
        sort_order,
        invoice_no,
        invoice_date,
        product_code,
        product_name,
        quantity,
        vat,
        payment,
        pre_tax,
        promo,
        promo_flag,
        tax_status,
        invoice_status,
        issued
    )
    select
        v_id,
        coalesce((x.elem ->> 'sortOrder')::integer, x.ordinality::integer),
        coalesce(x.elem ->> 'invoiceNo', ''),
        nullif(x.elem ->> 'invoiceDate', '')::date,
        coalesce(x.elem ->> 'productCode', ''),
        coalesce(x.elem ->> 'productName', ''),
        coalesce((x.elem ->> 'quantity')::numeric, 0),
        coalesce((x.elem ->> 'vat')::numeric, 0),
        coalesce((x.elem ->> 'payment')::numeric, 0),
        coalesce((x.elem ->> 'preTax')::numeric, 0),
        coalesce((x.elem ->> 'promo')::boolean, false),
        coalesce(x.elem ->> 'promoFlag', ''),
        coalesce(x.elem ->> 'taxStatus', ''),
        coalesce(x.elem ->> 'invoiceStatus', ''),
        coalesce((x.elem ->> 'issued')::boolean, true)
    from jsonb_array_elements(coalesce(p_lines, '[]'::jsonb))
         with ordinality as x(elem, ordinality);

    return jsonb_build_object(
        'id', v_id,
        'duplicate', false
    );
end;
$$;

-- -------------------------------------------------------------
-- 6. RPC xóa lịch sử: chỉ email ADMIN được phép.
-- -------------------------------------------------------------
create or replace function public.admin_delete_invoice_history(
    p_import_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_email text;
    v_deleted integer;
begin
    v_email := lower(coalesce(auth.jwt() ->> 'email', ''));

    if v_email <> 'lamtd9798@gmail.com' then
        raise exception 'Admin only';
    end if;

    delete from public.invoice_imports
    where id = p_import_id;

    get diagnostics v_deleted = row_count;

    return jsonb_build_object(
        'deleted', v_deleted,
        'id', p_import_id
    );
end;
$$;

-- -------------------------------------------------------------
-- 7. RPC health check AN TOÀN - chỉ đọc catalog, không ghi/xóa.
--    Thay cho cách đọc OpenAPI bị HTTP 401 ở V38.
-- -------------------------------------------------------------
create or replace function public.app_health_check()
returns jsonb
language sql
security definer
set search_path = public
as $$
select jsonb_build_object(
    'ok', true,
    'tables', jsonb_build_object(
        'invoice_imports', to_regclass('public.invoice_imports') is not null,
        'invoice_groups', to_regclass('public.invoice_groups') is not null,
        'invoice_lines', to_regclass('public.invoice_lines') is not null
    ),
    'rpcs', jsonb_build_object(
        'replace_shift_data', exists(
            select 1
            from pg_proc p
            join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'public'
              and p.proname = 'replace_shift_data'
        ),
        'admin_delete_shopee_data', exists(
            select 1
            from pg_proc p
            join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'public'
              and p.proname = 'admin_delete_shopee_data'
        ),
        'save_invoice_history', exists(
            select 1
            from pg_proc p
            join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'public'
              and p.proname = 'save_invoice_history'
        ),
        'admin_delete_invoice_history', exists(
            select 1
            from pg_proc p
            join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'public'
              and p.proname = 'admin_delete_invoice_history'
        )
    )
);
$$;

-- -------------------------------------------------------------
-- 8. Quyền function
-- -------------------------------------------------------------
revoke all on function public.save_invoice_history(jsonb, jsonb, jsonb) from public;
revoke all on function public.admin_delete_invoice_history(uuid) from public;
revoke all on function public.app_health_check() from public;

grant execute on function public.save_invoice_history(jsonb, jsonb, jsonb) to authenticated;
grant execute on function public.admin_delete_invoice_history(uuid) to authenticated;
grant execute on function public.app_health_check() to authenticated;

-- Cho authenticated SELECT theo RLS; sequence không cần vì insert qua SECURITY DEFINER.
grant select on public.invoice_imports to authenticated;
grant select on public.invoice_groups to authenticated;
grant select on public.invoice_lines to authenticated;

notify pgrst, 'reload schema';

-- -------------------------------------------------------------
-- 9. Kiểm tra cuối
-- -------------------------------------------------------------
select public.app_health_check() as v39_health_check;
