-- =============================================================
-- RUCOS V54 - MISA 3 FILE / GHÉP ĐƠN SHOPEE THEO MÃ ĐH CỦA SÀN
-- Chạy sau V53/V53.1. An toàn khi chạy lại.
-- =============================================================

create table if not exists public.misa_order_invoice_imports (
    id uuid primary key default gen_random_uuid(),
    import_type text not null check (import_type in ('published','unpublished')),
    file_hash text not null,
    file_name text not null default '',
    file_size bigint not null default 0,
    sheet_name text not null default '',
    source_row_count integer not null default 0,
    row_count integer not null default 0,
    filtered_out_count integer not null default 0,
    imported_at timestamptz not null default now(),
    created_by uuid default auth.uid(),
    created_email text not null default '',
    unique(import_type,file_hash)
);

create table if not exists public.misa_order_invoice_rows (
    id bigint generated by default as identity primary key,
    import_id uuid not null references public.misa_order_invoice_imports(id) on delete cascade,
    import_type text not null check (import_type in ('published','unpublished')),
    row_no integer not null,
    platform_order_id text not null default '',
    misa_order_id text not null default '',
    invoice_no text not null default '',
    invoice_date date,
    invoice_symbol text not null default '',
    total_payment numeric(20,2) not null default 0,
    order_status text not null default '',
    platform_payment_status text not null default '',
    order_created_at text not null default '',
    platform_paid_at text not null default '',
    channel text not null default '',
    shop text not null default '',
    invoice_type text not null default '',
    invoice_status text not null default '',
    issue_status text not null default '',
    tax_authority_status text not null default '',
    suggested_issue_at text not null default '',
    unissued_reason text not null default '',
    refund_request_id text not null default '',
    buyer_name text not null default '',
    store_name text not null default '',
    raw jsonb not null default '{}'::jsonb,
    unique(import_id,row_no)
);

create index if not exists idx_misa_order_rows_import on public.misa_order_invoice_rows(import_id);
create index if not exists idx_misa_order_rows_platform_order on public.misa_order_invoice_rows(platform_order_id) where platform_order_id<>'';
create index if not exists idx_misa_order_rows_invoice on public.misa_order_invoice_rows(invoice_no) where invoice_no<>'';
create index if not exists idx_misa_order_rows_misa_order on public.misa_order_invoice_rows(misa_order_id) where misa_order_id<>'';

alter table public.misa_order_invoice_imports enable row level security;
alter table public.misa_order_invoice_rows enable row level security;
grant select on public.misa_order_invoice_imports to authenticated;
grant select on public.misa_order_invoice_rows to authenticated;

drop policy if exists misa_order_imports_select_authenticated on public.misa_order_invoice_imports;
create policy misa_order_imports_select_authenticated on public.misa_order_invoice_imports for select to authenticated using(true);
drop policy if exists misa_order_rows_select_authenticated on public.misa_order_invoice_rows;
create policy misa_order_rows_select_authenticated on public.misa_order_invoice_rows for select to authenticated using(true);

create or replace function public.begin_misa_order_import_v54(p_import jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_role text:=public.app_current_role(); v_id uuid; v_type text:=coalesce(p_import->>'importType','');
begin
    if v_role not in ('ADMIN','KETOAN') then raise exception 'ROLE_FORBIDDEN_MISA_UPLOAD'; end if;
    if v_type not in ('published','unpublished') then raise exception 'INVALID_MISA_IMPORT_TYPE'; end if;
    insert into public.misa_order_invoice_imports(import_type,file_hash,file_name,file_size,sheet_name,source_row_count,row_count,filtered_out_count,imported_at,created_by,created_email)
    values(v_type,coalesce(p_import->>'fileHash',''),coalesce(p_import->>'fileName',''),coalesce((p_import->>'fileSize')::bigint,0),coalesce(p_import->>'sheetName',''),coalesce((p_import->>'sourceRowCount')::int,0),coalesce((p_import->>'rowCount')::int,0),coalesce((p_import->>'filteredOutCount')::int,0),now(),auth.uid(),coalesce(auth.jwt()->>'email',''))
    on conflict(import_type,file_hash) do update set file_name=excluded.file_name,file_size=excluded.file_size,sheet_name=excluded.sheet_name,source_row_count=excluded.source_row_count,row_count=excluded.row_count,filtered_out_count=excluded.filtered_out_count,imported_at=now(),created_by=auth.uid(),created_email=coalesce(auth.jwt()->>'email','')
    returning id into v_id;
    delete from public.misa_order_invoice_rows where import_id=v_id;
    return jsonb_build_object('import_id',v_id);
end;$$;

create or replace function public.append_misa_order_rows_v54(p_import_id uuid,p_rows jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_role text:=public.app_current_role(); v_type text; v_count int:=0;
begin
    if v_role not in ('ADMIN','KETOAN') then raise exception 'ROLE_FORBIDDEN_MISA_UPLOAD'; end if;
    select import_type into v_type from public.misa_order_invoice_imports where id=p_import_id;
    if v_type is null then raise exception 'MISA_IMPORT_NOT_FOUND'; end if;
    insert into public.misa_order_invoice_rows(import_id,import_type,row_no,platform_order_id,misa_order_id,invoice_no,invoice_date,invoice_symbol,total_payment,order_status,platform_payment_status,order_created_at,platform_paid_at,channel,shop,invoice_type,invoice_status,issue_status,tax_authority_status,suggested_issue_at,unissued_reason,refund_request_id,buyer_name,store_name,raw)
    select p_import_id,v_type,coalesce(nullif(x.elem->>'rowNo','')::int,x.ord::int),coalesce(x.elem->>'platformOrderId',''),coalesce(x.elem->>'misaOrderId',''),coalesce(x.elem->>'invoiceNo',''),nullif(x.elem->>'invoiceDate','')::date,coalesce(x.elem->>'invoiceSymbol',''),coalesce((x.elem->>'totalPayment')::numeric,0),coalesce(x.elem->>'orderStatus',''),coalesce(x.elem->>'platformPaymentStatus',''),coalesce(x.elem->>'orderCreatedAt',''),coalesce(x.elem->>'platformPaidAt',''),coalesce(x.elem->>'channel',''),coalesce(x.elem->>'shop',''),coalesce(x.elem->>'invoiceType',''),coalesce(x.elem->>'invoiceStatus',''),coalesce(x.elem->>'issueStatus',''),coalesce(x.elem->>'taxAuthorityStatus',''),coalesce(x.elem->>'suggestedIssueAt',''),coalesce(x.elem->>'unissuedReason',''),coalesce(x.elem->>'refundRequestId',''),coalesce(x.elem->>'buyerName',''),coalesce(x.elem->>'storeName',''),coalesce(x.elem->'raw','{}'::jsonb)
    from jsonb_array_elements(coalesce(p_rows,'[]'::jsonb)) with ordinality x(elem,ord)
    on conflict(import_id,row_no) do update set platform_order_id=excluded.platform_order_id,misa_order_id=excluded.misa_order_id,invoice_no=excluded.invoice_no,invoice_date=excluded.invoice_date,invoice_symbol=excluded.invoice_symbol,total_payment=excluded.total_payment,order_status=excluded.order_status,platform_payment_status=excluded.platform_payment_status,order_created_at=excluded.order_created_at,platform_paid_at=excluded.platform_paid_at,channel=excluded.channel,shop=excluded.shop,invoice_type=excluded.invoice_type,invoice_status=excluded.invoice_status,issue_status=excluded.issue_status,tax_authority_status=excluded.tax_authority_status,suggested_issue_at=excluded.suggested_issue_at,unissued_reason=excluded.unissued_reason,refund_request_id=excluded.refund_request_id,buyer_name=excluded.buyer_name,store_name=excluded.store_name,raw=excluded.raw;
    get diagnostics v_count=row_count;
    return jsonb_build_object('saved',v_count);
end;$$;

create or replace function public.finalize_misa_order_import_v54(p_import_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_role text:=public.app_current_role(); v_type text; v_links int:=0;
begin
    if v_role not in ('ADMIN','KETOAN') then raise exception 'ROLE_FORBIDDEN_MISA_UPLOAD'; end if;
    select import_type into v_type from public.misa_order_invoice_imports where id=p_import_id;
    if v_type='published' and to_regclass('public.invoice_order_links') is not null then
        insert into public.invoice_order_links(shopee_order_id,invoice_no,invoice_date,source,confidence,note,created_by,created_email,created_at,updated_at)
        select distinct r.platform_order_id,r.invoice_no,r.invoice_date,'misa_direct','exact','Tự động V54 từ Mã ĐH của sàn',auth.uid(),coalesce(auth.jwt()->>'email',''),now(),now()
        from public.misa_order_invoice_rows r
        where r.import_id=p_import_id and r.platform_order_id<>'' and r.invoice_no<>''
          and exists(select 1 from public.shopee_rows s where s.order_id=r.platform_order_id)
        on conflict do nothing;
        get diagnostics v_links=row_count;
    end if;
    return jsonb_build_object('auto_links',v_links);
end;$$;

create or replace function public.admin_delete_misa_order_import_v54(p_import_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
    if public.app_current_role()<>'ADMIN' then raise exception 'ADMIN_ONLY'; end if;
    delete from public.misa_order_invoice_imports where id=p_import_id;
    return true;
end;$$;

revoke all on function public.begin_misa_order_import_v54(jsonb) from public;
revoke all on function public.append_misa_order_rows_v54(uuid,jsonb) from public;
revoke all on function public.finalize_misa_order_import_v54(uuid) from public;
revoke all on function public.admin_delete_misa_order_import_v54(uuid) from public;
grant execute on function public.begin_misa_order_import_v54(jsonb) to authenticated;
grant execute on function public.append_misa_order_rows_v54(uuid,jsonb) to authenticated;
grant execute on function public.finalize_misa_order_import_v54(uuid) to authenticated;
grant execute on function public.admin_delete_misa_order_import_v54(uuid) to authenticated;

-- Giữ lại 2 RPC ADMIN quan trọng nếu V53.1 chưa chạy.
create or replace function public.admin_delete_shopee_data(p_scope text,p_target text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_rows_deleted int:=0;v_imports_deleted int:=0;v_start date;v_end date;
begin
 if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
 if not public.app_has_role(array['ADMIN']) then raise exception 'ADMIN_ONLY'; end if;
 if p_scope='day' then v_start:=p_target::date; delete from public.shopee_rows where report_date=v_start;get diagnostics v_rows_deleted=row_count;delete from public.imports where report_date=v_start;get diagnostics v_imports_deleted=row_count;
 elsif p_scope='month' then v_start:=(p_target||'-01')::date;v_end:=(v_start+interval '1 month')::date;delete from public.shopee_rows where report_date>=v_start and report_date<v_end;get diagnostics v_rows_deleted=row_count;delete from public.imports where report_date>=v_start and report_date<v_end;get diagnostics v_imports_deleted=row_count;
 else raise exception 'INVALID_SCOPE'; end if;
 return jsonb_build_object('scope',p_scope,'target',p_target,'rows_deleted',v_rows_deleted,'imports_deleted',v_imports_deleted);
end;$$;
create or replace function public.admin_delete_invoice_history(p_import_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_deleted int;begin if not public.app_has_role(array['ADMIN']) then raise exception 'ADMIN_ONLY';end if;delete from public.invoice_imports where id=p_import_id;get diagnostics v_deleted=row_count;return jsonb_build_object('deleted',v_deleted,'id',p_import_id);end;$$;
revoke all on function public.admin_delete_shopee_data(text,text) from public;grant execute on function public.admin_delete_shopee_data(text,text) to authenticated;
revoke all on function public.admin_delete_invoice_history(uuid) from public;grant execute on function public.admin_delete_invoice_history(uuid) to authenticated;

create or replace function public.app_health_check()
returns jsonb language sql security definer set search_path=public as $$
select jsonb_build_object(
'ok',true,'version','V54','role',public.app_current_role(),
'tables',jsonb_build_object(
'app_user_roles',to_regclass('public.app_user_roles') is not null,'invoice_imports',to_regclass('public.invoice_imports') is not null,'invoice_groups',to_regclass('public.invoice_groups') is not null,'invoice_lines',to_regclass('public.invoice_lines') is not null,'invoice_order_links',to_regclass('public.invoice_order_links') is not null,'inventory_return_receipts',to_regclass('public.inventory_return_receipts') is not null,'finance_imports',to_regclass('public.finance_imports') is not null,'finance_rows',to_regclass('public.finance_rows') is not null,'misa_order_invoice_imports',to_regclass('public.misa_order_invoice_imports') is not null,'misa_order_invoice_rows',to_regclass('public.misa_order_invoice_rows') is not null),
'v41',jsonb_build_object('invoice_import_order_ref_header',exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoice_imports' and column_name='order_ref_header'),'invoice_import_order_ref_line_count',exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoice_imports' and column_name='order_ref_line_count'),'invoice_line_order_ref',exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoice_lines' and column_name='order_ref'),'invoice_line_order_ref_source',exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoice_lines' and column_name='order_ref_source')),
'v47',jsonb_build_object('stocktake_baseline_date',exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='baseline_date'),'stocktake_theoretical_qty',exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='theoretical_qty'),'stocktake_variance_qty',exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='variance_qty'),'stocktake_variance_value',exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='variance_value'),'stocktake_reconcile_status',exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_stocktakes' and column_name='reconcile_status')),
'v50',jsonb_build_object('invoice_order_links_ready',to_regclass('public.invoice_order_links') is not null),
'v51',jsonb_build_object('return_receipts_ready',to_regclass('public.inventory_return_receipts') is not null,'confirm_return_rpc',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='confirm_inventory_return_v51'),'reverse_return_rpc',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reverse_inventory_return_v51')),
'v52',jsonb_build_object('inventory_lead_time_days',exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_items' and column_name='lead_time_days'),'inventory_target_cover_days',exists(select 1 from information_schema.columns where table_schema='public' and table_name='inventory_items' and column_name='target_cover_days')),
'v53',jsonb_build_object('finance_imports_ready',to_regclass('public.finance_imports') is not null,'finance_rows_ready',to_regclass('public.finance_rows') is not null,'finance_begin_rpc',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='begin_finance_import_v53'),'finance_append_rpc',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='append_finance_rows_v53'),'finance_delete_rpc',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_delete_finance_import_v53')),
'v54',jsonb_build_object('misa_imports_ready',to_regclass('public.misa_order_invoice_imports') is not null,'misa_rows_ready',to_regclass('public.misa_order_invoice_rows') is not null,'misa_begin_rpc',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='begin_misa_order_import_v54'),'misa_append_rpc',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='append_misa_order_rows_v54'),'misa_finalize_rpc',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='finalize_misa_order_import_v54')),
'rpcs',jsonb_build_object('app_user_context',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='app_user_context'),'admin_list_user_roles',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_list_user_roles'),'admin_set_user_role',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_set_user_role'),'replace_shift_data',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='replace_shift_data'),'admin_delete_shopee_data',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_delete_shopee_data'),'save_invoice_history',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_invoice_history'),'admin_delete_invoice_history',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_delete_invoice_history'),'confirm_inventory_return_v51',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='confirm_inventory_return_v51'),'reverse_inventory_return_v51',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='reverse_inventory_return_v51'),'begin_finance_import_v53',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='begin_finance_import_v53'),'append_finance_rows_v53',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='append_finance_rows_v53'),'admin_delete_finance_import_v53',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_delete_finance_import_v53'),'begin_misa_order_import_v54',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='begin_misa_order_import_v54'),'append_misa_order_rows_v54',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='append_misa_order_rows_v54'),'finalize_misa_order_import_v54',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='finalize_misa_order_import_v54'))
);
$$;
revoke all on function public.app_health_check() from public;grant execute on function public.app_health_check() to authenticated;
notify pgrst,'reload schema';
select public.app_health_check() as v54_health_check;
